GRANT OWNERSHIP ON DATABASE WORKSPACE_PILOT_DATABASE TO ROLE ACCOUNTADMIN REVOKE CURRENT GRANTS;
DROP DATABASE WORKSPACE_PILOT_DATABASE;
DROP ROLE WORKSPACE_PILOT_ADMIN_ROLE;
DROP USER WORKSPACE_PILOT_ADMIN;
DROP ROLE WORKSPACE_PILOT_READONLY_ROLE;
DROP USER WORKSPACE_PILOT_READONLY;


