CREATE DATABASE WORKSPACE_PILOT_DATABASE;
CREATE ROLE WORKSPACE_PILOT_ADMIN_ROLE;
GRANT OWNERSHIP ON DATABASE WORKSPACE_PILOT_DBNAME TO ROLE WORKSPACE_PILOT_ADMIN_ROLE;
GRANT ALL PRIVILEGES ON DATABASE WORKSPACE_PILOT_DBNAME TO ROLE ACCOUNTADMIN;
GRANT USAGE ON WAREHOUSE DEV TO ROLE WORKSPACE_PILOT_ADMIN_ROLE;
CREATE USER WORKSPACE_PILOT_ADMIN 
    PASSWORD='123456' 
    DEFAULT_ROLE=WORKSPACE_PILOT_ADMIN_ROLE 
    MUST_CHANGE_PASSWORD=TRUE
;
GRANT ROLE WORKSPACE_PILOT_ADMIN_ROLE TO USER WORKSPACE_PILOT_ADMIN;

CREATE ROLE WORKSPACE_PILOT_READONLY_ROLE;
GRANT USAGE ON WAREHOUSE DEV TO ROLE WORKSPACE_PILOT_READONLY_ROLE;
GRANT USAGE ON DATABASE WORKSPACE_PILOT_DBNAME TO ROLE WORKSPACE_PILOT_READONLY_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE WORKSPACE_PILOT_DBNAME TO ROLE WORKSPACE_PILOT_READONLY_ROLE;

CREATE USER WORKSPACE_PILOT_READONLY 
    PASSWORD='123456' 
    DEFAULT_ROLE=WORKSPACE_PILOT_READONLY_ROLE 
    MUST_CHANGE_PASSWORD=TRUE
;
GRANT ROLE WORKSPACE_PILOT_READONLY_ROLE TO USER WORKSPACE_PILOT_READONLY;

-- create empty DEFAULT schema
CREATE SCHEMA WORKSPACE_PILOT_DBNAME.DEFAULT;
GRANT OWNERSHIP ON SCHEMA WORKSPACE_PILOT_DBNAME.DEFAULT TO ROLE WORKSPACE_PILOT_ADMIN_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE WORKSPACE_PILOT_DBNAME TO ROLE WORKSPACE_PILOT_READONLY_ROLE;
GRANT USAGE ON DATABASE WORKSPACE_PILOT_DBNAME TO ROLE WORKSPACE_PILOT_READONLY_ROLE;
